%% Matriz Regresora
                                                                                                                                               %                           1                                                                                                                                                                             2                                                                                     3                                                                                     4                                                                                       5                                                                                     6                                               7                         8                      9                                   10                                   11                     12                     13             14       15
MG = [                                                                                                                                                                     0,                                                                                                                                                                            0,                                                                                    0,                                                                                    0,                                                                                      0,                                                                                    0,                                              0,                        0,                     0,                                   0,                                   0,                     0,                     0,             0,       0;
(cos(q2 - q3)*cos(q4 + q6))/2 + (cos(q2 - q3)*cos(q4 - q6))/2 - sin(q2 - q3)*sin(q5)*sin(q6) - (cos(q2 - q3)*sin(q4 - q5)*sin(q6))/2 - (cos(q2 - q3)*sin(q4 + q5)*sin(q6))/2, (cos(q2 - q3)*sin(q4 - q6))/2 - (cos(q2 - q3)*sin(q4 + q6))/2 - sin(q2 - q3)*cos(q6)*sin(q5) - (cos(q2 - q3)*sin(q4 - q5)*cos(q6))/2 - (cos(q2 - q3)*sin(q4 + q5)*cos(q6))/2, (cos(q2 - q3)*cos(q4 + q5))/2 + sin(q2 - q3)*cos(q5) - (cos(q2 - q3)*cos(q4 - q5))/2, (cos(q2 - q3)*cos(q4 - q5))/2 - sin(q2 - q3)*cos(q5) - (cos(q2 - q3)*cos(q4 + q5))/2, - (cos(q2 - q3)*sin(q4 + q5))/2 - sin(q2 - q3)*sin(q5) - (cos(q2 - q3)*sin(q4 - q5))/2, (cos(q2 - q3)*cos(q4 + q5))/2 + sin(q2 - q3)*cos(q5) - (cos(q2 - q3)*cos(q4 - q5))/2,                           cos(q2 - q3)*cos(q4),    -cos(q2 - q3)*sin(q4),  cos(q2 - q3)*cos(q4),                cos(q2 - q3)*cos(q4),                cos(q2 - q3)*cos(q4),         -sin(q2 - q3),          cos(q2 - q3),       cos(q2), sin(q2);
                                                                          sin(q2 - q3)*sin(q5)*sin(q6) - cos(q2 - q3)*cos(q4)*cos(q6) + cos(q2 - q3)*cos(q5)*sin(q4)*sin(q6),                                                                           cos(q2 - q3)*cos(q4)*sin(q6) + sin(q2 - q3)*cos(q6)*sin(q5) + cos(q2 - q3)*cos(q5)*cos(q6)*sin(q4),                                  cos(q2 - q3)*sin(q4)*sin(q5) - sin(q2 - q3)*cos(q5),                                  sin(q2 - q3)*cos(q5) - cos(q2 - q3)*sin(q4)*sin(q5),                                    sin(q2 - q3)*sin(q5) + cos(q2 - q3)*cos(q5)*sin(q4),                                  cos(q2 - q3)*sin(q4)*sin(q5) - sin(q2 - q3)*cos(q5),                          -cos(q2 - q3)*cos(q4),     cos(q2 - q3)*sin(q4), -cos(q2 - q3)*cos(q4),               -cos(q2 - q3)*cos(q4),               -cos(q2 - q3)*cos(q4),          sin(q2 - q3),         -cos(q2 - q3),             0,       0;
                                                                                                         -sin(q2 - q3)*cos(q6)*sin(q4)- sin(q2 - q3)*cos(q4)*cos(q5)*sin(q6),                                                                                                           sin(q2 - q3)*sin(q4)*sin(q6)- sin(q2 - q3)*cos(q4)*cos(q5)*cos(q6),                                                        -sin(q2 - q3)*cos(q4)*sin(q5),                                                         sin(q2 - q3)*cos(q4)*sin(q5),                                                          -sin(q2 - q3)*cos(q4)*cos(q5),                                                        -sin(q2 - q3)*cos(q4)*sin(q5),                        (-sin(q2 - q3)*sin(q4)),    -sin(q2 - q3)*cos(q4), -sin(q2 - q3)*sin(q4),               -sin(q2 - q3)*sin(q4),               -sin(q2 - q3)*sin(q4),                     0,                     0,             0,       0;
                                                                                                               sin(q6)*(cos(q2 - q3)*cos(q5) + sin(q2 - q3)*sin(q4)*sin(q5)),                                                                                                                cos(q6)*(cos(q2 - q3)*cos(q5) + sin(q2 - q3)*sin(q4)*sin(q5)),                                (cos(q2 - q3)*sin(q5) - sin(q2 - q3)*cos(q5)*sin(q4)),                                 (-cos(q2 - q3)*sin(q5)+sin(q2 - q3)*cos(q5)*sin(q4)),                                    (cos(q2 - q3)*cos(q5)+sin(q2 - q3)*sin(q4)*sin(q5)),                                  (cos(q2 - q3)*sin(q5)-sin(q2 - q3)*cos(q5)*sin(q4)),                                              0,                        0,                     0,                                   0,                                   0,                     0,                     0,             0,       0;
                                                                       -(sin(q2 - q3)*cos(q4)*sin(q6) - cos(q2 - q3)*cos(q6)*sin(q5) + sin(q2 - q3)*cos(q5)*cos(q6)*sin(q4)),                                                                        -(sin(q2 - q3)*cos(q4)*cos(q6) + cos(q2 - q3)*sin(q5)*sin(q6) - sin(q2 - q3)*cos(q5)*sin(q4)*sin(q6)),                                                                                    0,                                                                                    0,                                                                                      0,                                                                                    0,                                              0,                        0,                     0,                                   0,                                   0,                     0,                     0,             0,       0];

P =[   m6*xc6;  %1  P1
       m6*yc6;  %2  P2
        m6*x5;  %3  P3
       m6*zc6;  %4  P4
       m5*yc5;  %5  P5
       m5*xc5;  %6  P6
m5*x4 + m6*x4;  %7  P7
       m4*yc4;  %8  P8
       m4*xc4;  %9  P9
        m6*z5;  %10 P10
       m5*zc5;  %11 P11
       m5*z4 - m4*y3 - m5*y3 - m6*y3 - m3*yc3 + m6*z4 + m4*zc4; %12
       m3*xc3;  %13
       m2*xc2;  %14
       - m3*y2 - m4*y2 - m5*y2 - m6*y2 - m2*yc2]*g;   

VG = MG*P;